In [1]:
import numpy as np

In [3]:
lines = [line.rstrip('\n') for line in open('nursery.data.txt')]

In [8]:
print(lines[0])
row = lines[0].split(',')
print(row)

usual,proper,complete,1,convenient,convenient,nonprob,recommended,recommend
['usual', 'proper', 'complete', '1', 'convenient', 'convenient', 'nonprob', 'recommended', 'recommend']


In [6]:
attr_names = ['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health']

In [26]:
attr_list = [['usual', 'pretentious','great_pret'],
['proper','less_proper','improper','critical','very_crit'],
['complete', 'completed', 'incomplete', 'foster'],
['1', '2', '3', 'more'],
['convenient', 'less_conv', 'critical'],
['convenient', 'inconv'],
['nonprob', 'slightly_prob', 'problematic'],
['recommended', 'priority', 'not_recom'],
['not_recom', 'recommend', 'very_recom', 'priority', 'spec_prior']]

In [27]:
data = []
for i in range(len(lines)-1):
    row = lines[i].split(',')
#     print(row)
    sample = []
    for j in range(len(row)):
#         print(attr_list[j])
#         print(row[j])
        sample.append(attr_list[j].index(row[j]))
#     print(sample)
    data.append(sample)
data = np.asarray(data)

In [12]:
from sklearn import datasets
iris = datasets.load_iris()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(iris.data, iris.target).predict(iris.data)
print("Number of mislabeled points out of a total %d points : %d"
      % (iris.data.shape[0],(iris.target != y_pred).sum()))

Number of mislabeled points out of a total 150 points : 6


In [32]:
print(iris.target.shape)

(150,)


In [28]:
print(data)

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 3]
 [0 0 0 ... 0 2 0]
 ...
 [2 4 3 ... 2 0 4]
 [2 4 3 ... 2 1 4]
 [2 4 3 ... 2 2 0]]


In [29]:
print(data.shape)

(12960, 9)


In [57]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
feature = data[:,0:8]
label = data[:,8].reshape(-1, 1)

gnb = GaussianNB()
y_pred = gnb.fit(feature, label).predict(label).reshape(-1, 1)
print("Number of mislabeled points out of a total %d points : %d"
      % (feature.shape[0],(label != y_pred).sum()))

Number of mislabeled points out of a total 12960 points : 8916


In [56]:
import numpy as np
feature = data[:,0:8]
label = data[:,8].reshape(-1, 1)

from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(feature, label)

y_pred = clf.predict(feature).reshape(-1, 1)

print("Number of mislabeled points out of a total %d points : %d"
      % (feature.shape[0],(label != y_pred).sum()))

Number of mislabeled points out of a total 12960 points : 3389


In [58]:
from sklearn import datasets
iris = datasets.load_iris()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(iris.data, iris.target).predict(iris.data)
print("Number of mislabeled points out of a total %d points : %d"
      % (iris.data.shape[0],(iris.target != y_pred).sum()))

Number of mislabeled points out of a total 150 points : 6
